# Release: https://github.com/zenopie/monero-bridge/releases/tag/v1.1.4
# Workflow URL: https://github.com/zenopie/monero-bridge/actions/runs/23736238852
# Commit: https://github.com/zenopie/monero-bridge/commit/20da1d5249ddebcb7b57e4b83df158dcb204b5cd
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/monero-bridge@sha256:e537555f67858a081e3dd70078f8a069556562b04b64a4d41b6b10509a81922e
    ports:
      - '8000'
      - '18080'
      - '18081'
