# Release: https://github.com/zenopie/monero-bridge/releases/tag/v1.1.2
# Workflow URL: https://github.com/zenopie/monero-bridge/actions/runs/23735299709
# Commit: https://github.com/zenopie/monero-bridge/commit/1e1f5f55e2b7d3419e6323669bb920d8d84816b4
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/monero-bridge@sha256:0865cf4d1374568d4a395e96076d5dc039325cbc69d1dc5fc0fb6a0bb4091577
    ports:
      - '8000'
      - '18080'
      - '18081'
