# Release: https://github.com/zenopie/monero-bridge/releases/tag/v0.1.0
# Workflow URL: https://github.com/zenopie/monero-bridge/actions/runs/23734190438
# Commit: https://github.com/zenopie/monero-bridge/commit/8c831e7f6bcd92815927f199a0dcd704bc9ebd88
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/monero-bridge@sha256:3b5bc6151dd23a5584828de31bfee0414d5ce7704b913612affdefe095058202
    ports:
      - '8000'
      - '18080'
      - '18081'
